spring:
  application.name: concert

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        show_sql: false
    defer-datasource-initialization: true

  sql:
    init:
      schema-locations: file:./docs/ddl.sql

  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    producer:
      retries: 3
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      metadata.max.age.ms: 3000
    properties.auto.create.topics.enable: false