services:
  consertService:
    image: concert
    container_name: concert
    build: ./build
    ports:
      - "8081:8080"
    environment:
      DB_URL: 
      DB_USER: 
      DB_PASSWORD: 
      REDIS_HOST: 
      REDIS_PORT: 
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092 
    networks:
      - spring-kafka-network
    deploy:
      resources:
        limits:
          cpus: "2.0"    # 최대 cpu    
          memory: "1g"   # 최대 memory    
        reservations:
          cpus: "1.0"    # 최소 cpu  
          memory: "500m" # 최소 memory      

networks:
  spring-kafka-network:
    external: true